#!/bin/bash
#mkfontimagexy FONT A B C 
#usage: 'mkfontimagexy nf.ttc 31 40 27'
#function mkfontimagexy()
#{
convert -size $2x$((235*$3)) xc:black -font "$1" -pointsize $4 -fill white -draw "@b.txt" -threshold 0% -depth 1 -flip $1.png
convert $1.png -depth 1 $1.bmp
dd bs=150 skip=1 if=$1.bmp of=$1.raw
xxd -i $1.raw $1.h
hexdump -v -e '"0x" 1/1 "%02X" ","' $1.raw >> $1.h
rm $1.bmp
#rm $1.raw
sed -i -r 's/\w+\[\]/Font'$3'_table\[\]/g' $1.h
sed -i -r 's/\w+_len/Font'$3'_len/g' $1.h
echo -e "\nsFONT Font"$3" = {\n  Font"$3"_table,\n  "$2", /* Width */\n  "$3", /* Height */\n};\n" >> $1.h
#}
